version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./:/usr/src/teste
    ports:
      - "4000:4000"
      - "9229:9229"
    command: sh -c 'npm i && npm run start'
  postgres:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres