version: '3'

services:
  postgres:
    container_name: postgresql
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: sympla
      POSTGRES_USER: sympla
      POSTGRES_DB: acervo_digital
      FILE_DATA_POSTGRES: ./backend/scripts/data.sql
    volumes:                                                                                                                                           
      - ./backend/scripts:/docker-entrypoint-initdb.d/
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - postgres
    volumes:
      - ./:/home/src/app
    ports:
      - "4000:4000"
      - "9229:9229"
    command: sh -c 'cd backend && npm i && npm run start'
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    volumes:
      - ./:/home/src/app
    ports:
      - "3000:3000"
    command: sh -c 'cd frontend && npm i && npm run dev'    